# PostgreSQL: logs and database metrics

receivers:
  postgresql:
    endpoint: postgres:5432
    username: observer
    password: ${POSTGRES_OBSERVER_PASSWORD}
    databases: [postgres, demo]
    collection_interval: 30s
    tls:
      insecure: true

processors:
  resource/postgresql:
    attributes:
      - key: service.name
        value: postgresql
        action: upsert
      - key: server.address
        value: postgres
        action: upsert
      - key: server.port
        value: "5432"
        action: upsert
      - key: db.system.name
        value: postgresql
        action: upsert

  # Rename metric attributes to OTel conventions
  transform/metrics:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["db.namespace"], attributes["postgresql_database_name"]) where attributes["postgresql_database_name"] != nil
          - delete_key(attributes, "postgresql_database_name")

  # Parse PostgreSQL logs
  transform/logs:
    log_statements:
      - context: log
        statements:
          # Set defaults
          - set(attributes["db.system.name"], "postgresql")
          - set(attributes["db.user"], "system")
          - set(attributes["db.namespace"], "system")
          - set(severity_text, "INFO")
          # Override severity based on log level
          - set(severity_text, "ERROR") where IsMatch(body, ".*ERROR:.*")
          - set(severity_text, "WARNING") where IsMatch(body, ".*WARNING:.*")
          - set(severity_text, "FATAL") where IsMatch(body, ".*FATAL:.*")
          - set(severity_text, "PANIC") where IsMatch(body, ".*PANIC:.*")
          - set(severity_text, "DEBUG") where IsMatch(body, ".*DEBUG:.*")
          - set(severity_text, "NOTICE") where IsMatch(body, ".*NOTICE:.*")
          # Extract db.user
          - set(attributes["db.user"], "observer") where IsMatch(body, ".*user=observer.*")
          - set(attributes["db.user"], "demo_app") where IsMatch(body, ".*user=demo_app.*")
          - set(attributes["db.user"], "postgres") where IsMatch(body, ".*user=postgres.*")
          # Extract db.namespace
          - set(attributes["db.namespace"], "demo") where IsMatch(body, ".*database=demo.*")
          - set(attributes["db.namespace"], "postgres") where IsMatch(body, ".*database=postgres.*")
          # Remove unnecessary attributes
          - delete_key(attributes, "log.file.name")
          - delete_key(attributes, "log.file.path")
          - delete_key(attributes, "log.iostream")
          - delete_key(resource.attributes, "container.id")

exporters:
  otlphttp/database:
    endpoint: http://openobserve:5080/api/default
    headers:
      Authorization: Basic ${ZO_INGESTION_TOKEN}
      stream-name: database
    tls:
      insecure: true

service:
  pipelines:
    logs/database:
      receivers: [routing/logs]
      processors: [transform/logs, batch]
      exporters: [otlphttp/database]
    metrics/postgresql:
      receivers: [postgresql]
      processors: [memory_limiter, resource/postgresql, transform/metrics, batch, resource]
      exporters: [otlphttp/openobserve]
